### ISSUE TITLE
Fatal error - MacOS

### ISSUE THREAD

**Issue by gjt211** [arduino-libraries/WiFi101-FirmwareUpdater#10]
Hi, I am trying to run this on my Mac without success.
What I need to do is use a self signed certificate and by adding it through the WiFi101Firmware updater in the IDE it says it has been successful but I still can't connect.

Here is the terminal output from running `winc1500-uploader-gui` on my Mac.
```
Last login: Sun Sep  9 15:10:16 on ttys000
Glendons-Mac-mini:~ gjt211$ /Users/gjt211/Downloads/Wifi101_FirmwareUpdater/winc1500-uploader-gui ; exit;
failed MSpanList_Insert 0x4db0000 0x824897ffb04 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x4b8f18b)
	/opt/go/src/runtime/panic.go:491 +0xad fp=0x7ffeefbff680 sp=0x7ffeefbff650
runtime.MSpanList_Insert(0x4be3888, 0x4db0000)
	/opt/go/src/runtime/mheap.c:692 +0x8f fp=0x7ffeefbff6a8 sp=0x7ffeefbff680
MHeap_FreeSpanLocked(0x4be0480, 0x4db0000, 0x100)
	/opt/go/src/runtime/mheap.c:583 +0x163 fp=0x7ffeefbff6e8 sp=0x7ffeefbff6a8
MHeap_Grow(0x4be0480, 0x8, 0x0)
	/opt/go/src/runtime/mheap.c:420 +0x1a8 fp=0x7ffeefbff728 sp=0x7ffeefbff6e8
MHeap_AllocSpanLocked(0x4be0480, 0x1, 0x0)
	/opt/go/src/runtime/mheap.c:298 +0x365 fp=0x7ffeefbff768 sp=0x7ffeefbff728
mheap_alloc(0x4be0480, 0x1, 0x12, 0x0)
	/opt/go/src/runtime/mheap.c:190 +0x121 fp=0x7ffeefbff790 sp=0x7ffeefbff768
runtime.MHeap_Alloc(0x4be0480, 0x1, 0x10000000012, 0x40327e9)
	/opt/go/src/runtime/mheap.c:240 +0x66 fp=0x7ffeefbff7c8 sp=0x7ffeefbff790
MCentral_Grow(0x4be81f8, 0x0)
	/opt/go/src/runtime/mcentral.c:197 +0x8b fp=0x7ffeefbff830 sp=0x7ffeefbff7c8
runtime.MCentral_CacheSpan(0x4be81f8, 0x0)
	/opt/go/src/runtime/mcentral.c:85 +0x167 fp=0x7ffeefbff868 sp=0x7ffeefbff830
runtime.MCache_Refill(0x4dac000, 0x12, 0x0)
	/opt/go/src/runtime/mcache.c:90 +0xa0 fp=0x7ffeefbff890 sp=0x7ffeefbff868
runtime.mcacheRefill_m()
	/opt/go/src/runtime/malloc.c:368 +0x57 fp=0x7ffeefbff8b0 sp=0x7ffeefbff890
runtime.onM(0x49d2fb0)
	/opt/go/src/runtime/asm_amd64.s:273 +0x9a fp=0x7ffeefbff8b8 sp=0x7ffeefbff8b0
runtime.mallocgc(0x120, 0x450b3a0, 0x0, 0x0)
	/opt/go/src/runtime/malloc.go:178 +0x849 fp=0x7ffeefbff968 sp=0x7ffeefbff8b8
runtime.newobject(0x450b3a0, 0x4dac000)
	/opt/go/src/runtime/malloc.go:353 +0x49 fp=0x7ffeefbff990 sp=0x7ffeefbff968
runtime.newG(0x404b97a)
	/opt/go/src/runtime/proc.go:233 +0x2a fp=0x7ffeefbff9a8 sp=0x7ffeefbff990
allocg(0x4bd0b60)
	/opt/go/src/runtime/proc.c:925 +0x1f fp=0x7ffeefbff9b8 sp=0x7ffeefbff9a8
runtime.malg(0x8000, 0x4bd0d20)
	/opt/go/src/runtime/proc.c:2106 +0x1f fp=0x7ffeefbff9e8 sp=0x7ffeefbff9b8
runtime.mpreinit(0x4bd10e0)
	/opt/go/src/runtime/os_darwin.c:137 +0x27 fp=0x7ffeefbffa00 sp=0x7ffeefbff9e8
mcommoninit(0x4bd10e0)
	/opt/go/src/runtime/proc.c:201 +0xc9 fp=0x7ffeefbffa28 sp=0x7ffeefbffa00
runtime.schedinit()
	/opt/go/src/runtime/proc.c:138 +0x55 fp=0x7ffeefbffa50 sp=0x7ffeefbffa28
runtime.rt0_go(0x7ffeefbffa90, 0x1, 0x7ffeefbffa90, 0x0, 0x4001d84, 0x0, 0x1, 0x7ffeefbffbd0, 0x0, 0x7ffeefbffc16, ...)
	/opt/go/src/runtime/asm_amd64.s:95 +0x116 fp=0x7ffeefbffa58 sp=0x7ffeefbffa50
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by facchinm** [comment]
Hi @gjt211 ,
the error is due to new versions of macOS breaking go programs compiled in the past; since we are not maintaining this project anymore I can only attach the `cli` version just recompiled for modern OSX.
For the self signed certificate problem, please open an issue in the other (Java) firmware updater. Thanks!
[winc1500-uploader.zip](https://github.com/arduino-libraries/WiFi101-FirmwareUpdater/files/2365669/winc1500-uploader.zip)

**Comment by gjt211** [comment]
Hi @facchinm,
Thanks for your informative reply.

Does your comment about this not being maintained anymore only refer to this updater like I think it does? I am concerned if it includes the WINC1500 as I was planning on using in for some years to come unless you can recommend a non-espressif option I could investigate.
Once agin, thanks for your reply and recompiling the code for me.

**Comment by facchinm** [comment]
Yes, it's only about this updater :slightly_smiling_face: The [other updater](https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin) and the WINC chip are going to be supported for a looong time

**Comment by gjt211** [comment]
Cool, thanks again!

Sorry, but I would like to ask one more question please - hopefully you can just point me in the right direction.

I have just uploaded my rootCA certificate after converting it from PEM to CRT using OPENSSL but it still does not work. I have been searching for days and I think it may be because the certificate is self signed. I seen a comment somewhere about the need to possibly modify a specific line in a file located in a java folder in the IDE location. On my mac, I was unable to find the mentioned file.

Do you know anything about using self signed certificates? They work fine on other (Arduino-ESP) platforms.

**Comment by facchinm** [comment]
This is quite strange frankly; the Java updater is known to have problems doing this since it validates the certificates against its own chain of trust, but if you were able to upload the self signed certificate I see no reason why it shouldn't work. Feel free to open an issue in the other repository about adding self-signed certificates and we'll surely take a look!

**Comment by gjt211** [comment]
#22 created thanks.
