### ISSUE TITLE
Include Baltimore CA cert by default

### ISSUE THREAD

**Issue by stefangordon** [arduino-libraries/WiFi101-FirmwareUpdater#2]
We should include the cert for Azure as many users will integrate with Azure IOT services.  This can be pulled from https://www.microsoft.com

**Comment by ladyada** [comment]
heya, i forked, and added the baltimore here https://github.com/adafruit/WiFi101-FirmwareUpdater
i tested it and could ssl to anprice-iothub.azure-devices.ne

**Comment by stefangordon** [comment]
Great!
