### ISSUE TITLE
wifi101 firmware updater query

### ISSUE THREAD

**Issue by sudheera8** [arduino-libraries/WiFi101-FirmwareUpdater#7]
Hi @sandeepmistry 

I am using the firmware updater GUI to upload an SSL certificate corresponding to my server in to my module.
 I am also changing the PPA value and the gain table of the wifi module's firmware using an Atmel ASF project and then using your GUI to add a certificate to it.

Question: does the certificate updater GUI erase the entire flash of the wifi module or just updates the certificate section? I assume its just an update but I wanted to verify.

Thanks a lot
Sudheera

**Comment by sandeepmistry** [comment]
It erases the entire flash and overwrites it with the binary image supplied by Microchip/Atmel.
