### ISSUE TITLE
19.5.2 firmware download

### ISSUE THREAD

**Issue by KidA001** [arduino-libraries/WiFi101-FirmwareUpdater#8]
I need to update my Wifi101 to 19.5.2 - I read that it only works on `ATSAMW25H18-MR510PB → WINC1500 Model B` which is what I have.

I have been unable to find that firmware anywhere and cannot use the built-in updated on the Arduino editor, I can only use CLI. Can someone point me to where I can download this firmware?

**Comment by KidA001** [comment]
Anyone?

**Comment by sandeepmistry** [comment]
Hi @KidA001,

Firmware binaries can be download from Atmel Studio. This repo has been superseded by the following https://github.com/arduino-libraries/WiFi101-FirmwareUpdater-Plugin which also contains a copy of firmware binaries.
